language: python
python:
  - "2.7"
sudo: false
addons:
  apt_packages:
  - gawk
  - wget
  - git-core
  - diffstat
  - unzip
  - texinfo
  - gcc-multilib
  - build-essential
  - chrpath
  - socat
  - libsdl1.2-dev
  - xterm

before_install:
  - git clone https://github.com/rossburton/bitbake.git

script:
  - BB_SKIP_NETTESTS=yes ./bitbake/bin/bitbake-selftest
  - . ./oe-init-build-env
  - MACHINE=qemux86 bitbake gcc-cross-i586 | cat
