language: python
python:
  - "2.7"
sudo: false
addons:
  apt_packages:
  - diffstat
  - texinfo
  - chrpath

before_install:
  - git clone https://github.com/rossburton/bitbake.git

script:
  - BB_SKIP_NETTESTS=yes ./bitbake/bin/bitbake-selftest
  - . ./oe-init-build-env
  - echo 'PACKAGECONFIG_remove_pn-qemu-native = "sdl"' >> conf/local.conf
  - echo 'ASSUME_PROVIDED_remove = "diffstat-native libsdl-native"' >> conf/local.conf
  - echo "# Temporary hack" > conf/sanity.conf
  - MACHINE=qemux86 bitbake gcc-cross-i586 | cat
