language: python
python:
  - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install --quiet --yes gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat libsdl1.2-dev xterm
  - git clone https://github.com/rossburton/bitbake.git

script:
  - BB_SKIP_NETTESTS=yes ./bitbake/bin/bitbake-selftest
  - . ./oe-init-build-env
  - bitbake --version
  - MACHINE=qemux86 bitbake gcc-cross-i586